# Generated by Powerlevel10k configuration wizard (customized)
# Run `p10k configure` to reconfigure interactively.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Prompt mode: rainbow (colored segments with icons)
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3

  # Left prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )

  # Right prompt segments
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of last command
    command_execution_time  # duration of last command
    background_jobs         # background job indicator
    direnv                  # direnv status
    dotnet_version          # .NET version
    node_version            # Node.js version
    python_env              # Python virtualenv
    docker_context          # Docker context (when not default)
    azure                   # Azure account
    context                 # user@host (SSH only)
  )

  # === Visual Style ===
  typeset -g POWERLEVEL9K_BACKGROUND=                          # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # space between segments
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no separator chars

  # === Prompt Character ===
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76    # green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196 # red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true

  # === Directory ===
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31                    # blue
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103         # dimmer blue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39             # bright blue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.shorten_folder_marker|.bzr|CVS|.git|.hg|.svn|.terraform|.citc|.info|.p4root|package.json|*.csproj|*.fsproj|*.sln)'
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # === Git (VCS) ===
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76              # green
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178          # yellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=178         # yellow
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196        # red
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244           # grey
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED}_MAX_NUM=99
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=99
  typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=99

  # === Command Execution Time ===
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2   # show if >2s
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=178 # yellow
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=

  # === Exit Status ===
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false                      # hide on success
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196           # red
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=196
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=196

  # === Background Jobs ===
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⇣'

  # === Context (user@host, SSH only) ===
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION=
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=178
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_CONTENT_EXPANSION='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=180

  # === .NET ===
  typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=134         # purple
  typeset -g POWERLEVEL9K_DOTNET_VERSION_VISUAL_IDENTIFIER_EXPANSION='󰪮'

  # === Node.js ===
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=70            # green
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # === Python ===
  typeset -g POWERLEVEL9K_PYTHON_ENV_FOREGROUND=37
  typeset -g POWERLEVEL9K_PYTHON_ENV_SHOW_SYSTEM_VENV=false

  # === Docker Context ===
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_FOREGROUND=32
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_{DEFAULT,COLIMA}_CONTENT_EXPANSION=  # hide default
  typeset -g POWERLEVEL9K_DOCKER_CONTEXT_VISUAL_IDENTIFIER_EXPANSION=' '

  # === Azure ===
  typeset -g POWERLEVEL9K_AZURE_FOREGROUND=32
  typeset -g POWERLEVEL9K_AZURE_VISUAL_IDENTIFIER_EXPANSION='󰠅'

  # === direnv ===
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=178

  # === Transient Prompt ===
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=same-dir            # collapse when staying in same dir

  # === Instant Prompt ===
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # === Misc ===
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true              # run `source ~/.p10k.zsh` after changes

  (( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
  'builtin' 'unset' 'p10k_config_opts'
}
