-- ============================================================
-- Catppuccin Frappé
-- ============================================================

vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd.syntax("reset")
end
vim.g.colors_name = "catppuccin-frappe"

local p = {
    rosewater = "#f2d5cf",
    flamingo  = "#eebebe",
    pink      = "#f4b8e4",
    mauve     = "#ca9ee6",
    red       = "#e78284",
    maroon    = "#ea999c",
    peach     = "#ef9f76",
    yellow    = "#e5c890",
    green     = "#a6d189",
    teal      = "#81c8be",
    sky       = "#99d1db",
    sapphire  = "#85c1dc",
    blue      = "#8caaee",
    lavender  = "#babbf1",
    text      = "#c6d0f5",
    subtext1  = "#b5bfe2",
    subtext0  = "#a5adce",
    overlay2  = "#949cbb",
    overlay1  = "#838ba7",
    overlay0  = "#737994",
    surface2  = "#626880",
    surface1  = "#51576d",
    surface0  = "#414559",
    base      = "#303446",
    mantle    = "#292c3c",
    crust     = "#232634",
}

local hl = {
    -- --- UI ---
    Normal       = { fg = p.text, bg = p.base },
    NormalFloat  = { fg = p.text, bg = p.mantle },
    FloatBorder  = { fg = p.blue, bg = p.mantle },
    Cursor       = { fg = p.base, bg = p.rosewater },
    CursorLine   = { bg = p.surface0 },
    CursorLineNr = { fg = p.peach, bold = true },
    LineNr       = { fg = p.surface1 },
    ColorColumn  = { bg = p.surface0 },
    SignColumn   = { fg = p.surface1 },
    Visual       = { bg = p.surface1 },
    Search       = { fg = p.base, bg = p.yellow },
    IncSearch    = { fg = p.base, bg = p.peach },
    CurSearch    = { fg = p.base, bg = p.red },
    StatusLine   = { fg = p.text, bg = p.mantle },
    StatusLineNC = { fg = p.overlay0, bg = p.mantle },
    WinSeparator = { fg = p.surface0 },
    Pmenu        = { fg = p.text, bg = p.surface0 },
    PmenuSel     = { fg = p.base, bg = p.blue, bold = true },
    PmenuSbar    = { bg = p.surface1 },
    PmenuThumb   = { bg = p.overlay0 },
    WildMenu     = { bg = p.overlay0 },
    MatchParen   = { fg = p.peach, bold = true },
    NonText      = { fg = p.surface1 },
    Whitespace   = { fg = p.surface1 },
    SpecialKey   = { fg = p.surface2 },
    EndOfBuffer  = { fg = p.base },
    Folded       = { fg = p.blue, bg = p.surface0 },
    Conceal      = { fg = p.overlay1 },
    Directory    = { fg = p.blue },
    Title        = { fg = p.blue, bold = true },
    ErrorMsg     = { fg = p.red, bold = true },
    WarningMsg   = { fg = p.yellow },
    ModeMsg      = { fg = p.text, bold = true },
    MoreMsg      = { fg = p.green },
    Question     = { fg = p.green },
    QuickFixLine = { bg = p.surface1, bold = true },

    -- --- Syntax ---
    Comment      = { fg = p.overlay1, italic = true },
    Constant     = { fg = p.peach },
    String       = { fg = p.green },
    Character    = { fg = p.teal },
    Number       = { fg = p.peach },
    Boolean      = { fg = p.peach },
    Float        = { fg = p.peach },
    Identifier   = { fg = p.flamingo },
    Function     = { fg = p.blue },
    Statement    = { fg = p.mauve },
    Conditional  = { fg = p.mauve },
    Repeat       = { fg = p.mauve },
    Label        = { fg = p.sapphire },
    Operator     = { fg = p.sky },
    Keyword      = { fg = p.mauve },
    Exception    = { fg = p.mauve },
    PreProc      = { fg = p.pink },
    Include      = { fg = p.mauve },
    Define       = { fg = p.pink },
    Macro        = { fg = p.mauve },
    Type         = { fg = p.yellow },
    StorageClass = { fg = p.yellow },
    Structure    = { fg = p.yellow },
    Typedef      = { fg = p.yellow },
    Special      = { fg = p.pink },
    Delimiter    = { fg = p.overlay2 },
    Underlined   = { fg = p.blue, underline = true },
    Error        = { fg = p.red },
    Todo         = { fg = p.base, bg = p.yellow, bold = true },

    -- --- Diff & git ---
    DiffAdd      = { bg = "#485353" },
    DiffChange   = { bg = "#424c68" },
    DiffDelete   = { bg = "#554452" },
    DiffText     = { bg = "#505d81" },
    Added        = { fg = p.green },
    Changed      = { fg = p.yellow },
    Removed      = { fg = p.red },

    -- --- Treesitter captures ---
    ["@comment"]               = { link = "Comment" },
    ["@string"]                = { link = "String" },
    ["@character"]             = { link = "Character" },
    ["@number"]                = { link = "Number" },
    ["@boolean"]               = { link = "Boolean" },
    ["@function"]              = { link = "Function" },
    ["@function.call"]         = { link = "Function" },
    ["@function.builtin"]      = { fg = p.peach },
    ["@constructor"]           = { fg = p.sapphire },
    ["@keyword"]               = { link = "Keyword" },
    ["@keyword.operator"]      = { fg = p.mauve },
    ["@type"]                  = { link = "Type" },
    ["@type.builtin"]          = { fg = p.yellow, italic = true },
    ["@variable"]              = { fg = p.text },
    ["@variable.builtin"]      = { fg = p.red },
    ["@variable.member"]       = { fg = p.lavender },
    ["@variable.parameter"]    = { fg = p.maroon, italic = true },
    ["@property"]              = { fg = p.lavender },
    ["@constant"]              = { link = "Constant" },
    ["@constant.builtin"]      = { fg = p.peach },
    ["@operator"]              = { link = "Operator" },
    ["@punctuation.delimiter"] = { fg = p.overlay2 },
    ["@punctuation.bracket"]   = { fg = p.overlay2 },
    ["@punctuation.special"]   = { fg = p.sky },
    ["@tag"]                   = { fg = p.mauve },
    ["@tag.attribute"]         = { fg = p.teal, italic = true },
    ["@tag.delimiter"]         = { fg = p.sky },
    ["@markup.heading"]        = { fg = p.blue, bold = true },
    ["@markup.strong"]         = { bold = true },
    ["@markup.italic"]         = { italic = true },
    ["@markup.link"]           = { fg = p.blue, underline = true },
    ["@markup.raw"]            = { fg = p.green },
    ["@markup.list"]           = { fg = p.peach },
    ["@diff.plus"]             = { fg = p.green },
    ["@diff.minus"]            = { fg = p.red },
}

for group, opts in pairs(hl) do
    vim.api.nvim_set_hl(0, group, opts)
end
